// Netflix content data and management
export const contentGenres = [
  { id: 'all', name: 'All Content', icon: 'fas fa-th' },
  { id: 'action', name: 'Action', icon: 'fas fa-fist-raised' },
  { id: 'comedy', name: 'Comedy', icon: 'fas fa-laugh' },
  { id: 'drama', name: 'Drama', icon: 'fas fa-theater-masks' },
  { id: 'thriller', name: 'Thriller', icon: 'fas fa-eye' },
  { id: 'documentary', name: 'Documentary', icon: 'fas fa-video' },
  { id: 'romance', name: 'Romance', icon: 'fas fa-heart' },
  { id: 'horror', name: 'Horror', icon: 'fas fa-ghost' },
  { id: 'sci-fi', name: 'Sci-Fi', icon: 'fas fa-rocket' },
  { id: 'animation', name: 'Animation', icon: 'fas fa-palette' }
];

export const netflixContent = [
  // Action Series
  { id: 1, title: 'Stranger Things', type: 'series', genre: 'action', rating: 8.7, year: 2016, seasons: 4, episodes: 42, description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 95, viewingHours: 2400000 },
  { id: 2, title: 'The Witcher', type: 'series', genre: 'action', rating: 8.2, year: 2019, seasons: 3, episodes: 24, description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 88, viewingHours: 1800000 },
  { id: 3, title: 'Money Heist', type: 'series', genre: 'action', rating: 8.3, year: 2017, seasons: 5, episodes: 41, description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 91, viewingHours: 2100000 },
  { id: 4, title: 'Cobra Kai', type: 'series', genre: 'action', rating: 8.5, year: 2018, seasons: 5, episodes: 50, description: 'Decades after the tournament that changed their lives, the rivalry between Johnny and Daniel reignites in this sequel to the Karate Kid films.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 89, viewingHours: 1950000 },
  { id: 5, title: 'Squid Game', type: 'series', genre: 'action', rating: 8.0, year: 2021, seasons: 1, episodes: 9, description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games for a tempting prize, but the stakes are deadly.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 97, viewingHours: 2800000 },
  { id: 6, title: 'Ozark', type: 'series', genre: 'action', rating: 8.4, year: 2017, seasons: 4, episodes: 44, description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 86, viewingHours: 1850000 },
  { id: 7, title: 'Narcos', type: 'series', genre: 'action', rating: 8.8, year: 2015, seasons: 3, episodes: 30, description: 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 90, viewingHours: 2200000 },
  { id: 8, title: 'Vikings: Valhalla', type: 'series', genre: 'action', rating: 7.2, year: 2022, seasons: 2, episodes: 16, description: 'In this sequel to Vikings, a hundred years have passed and a new generation of legendary heroes arises to forge their own destiny.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 1200000 },
  { id: 9, title: 'The Umbrella Academy', type: 'series', genre: 'action', rating: 7.9, year: 2019, seasons: 3, episodes: 30, description: 'A dysfunctional family of superheroes comes together to solve the mystery of their father\'s death, the threat of the apocalypse and more.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1650000 },
  { id: 10, title: 'Lupin', type: 'series', genre: 'action', rating: 7.5, year: 2021, seasons: 2, episodes: 10, description: 'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 1400000 },

  // Action Movies
  { id: 11, title: 'Extraction', type: 'movie', genre: 'action', rating: 6.8, year: 2020, runtime: 116, description: 'A black market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 950000 },
  { id: 12, title: 'Red Notice', type: 'movie', genre: 'action', rating: 6.4, year: 2021, runtime: 118, description: 'An FBI profiler pursuing the world\'s most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who\'s always one step ahead.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 890000 },
  { id: 13, title: '6 Underground', type: 'movie', genre: 'action', rating: 6.1, year: 2019, runtime: 128, description: 'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 75, viewingHours: 820000 },
  { id: 14, title: 'The Gray Man', type: 'movie', genre: 'action', rating: 6.5, year: 2022, runtime: 122, description: 'When the CIA\'s most skilled mercenary known as Court Gentry accidentally uncovers dark agency secrets, he becomes a primary target.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 77, viewingHours: 1050000 },
  { id: 15, title: 'Triple Frontier', type: 'movie', genre: 'action', rating: 6.5, year: 2019, runtime: 125, description: 'Struggling to make ends meet, former special ops soldiers reunite for a high-stakes heist: stealing $75 million from a South American drug lord.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 73, viewingHours: 780000 },

  // Comedy Series
  { id: 16, title: 'The Good Place', type: 'series', genre: 'comedy', rating: 8.2, year: 2016, seasons: 4, episodes: 50, description: 'A woman struggles to be a good person when she realizes she\'s been mistakenly sent to the Good Place instead of the Bad Place.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 87, viewingHours: 1600000 },
  { id: 17, title: 'Brooklyn Nine-Nine', type: 'series', genre: 'comedy', rating: 8.4, year: 2013, seasons: 8, episodes: 153, description: 'Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 89, viewingHours: 1750000 },
  { id: 18, title: 'Schitt\'s Creek', type: 'series', genre: 'comedy', rating: 8.5, year: 2015, seasons: 6, episodes: 80, description: 'When a wealthy family suddenly finds themselves broke, they are forced to leave their pampered lives to regroup in Schitt\'s Creek.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 92, viewingHours: 1950000 },
  { id: 19, title: 'Never Have I Ever', type: 'series', genre: 'comedy', rating: 7.8, year: 2020, seasons: 4, episodes: 40, description: 'A coming-of-age comedy-drama about the complicated life of a modern-day first-generation Indian American teenage girl.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1350000 },
  { id: 20, title: 'Space Force', type: 'series', genre: 'comedy', rating: 6.7, year: 2020, seasons: 2, episodes: 17, description: 'A decorated pilot with dreams of running the Air Force is thrown together with an eccentric scientist to get the U.S. military\'s newest agency off the ground.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 71, viewingHours: 950000 },
  { id: 21, title: 'Emily in Paris', type: 'series', genre: 'comedy', rating: 6.8, year: 2020, seasons: 3, episodes: 30, description: 'A young American woman from the Midwest is hired by a marketing firm in Paris to provide them with an American perspective on things.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 1400000 },
  { id: 22, title: 'The Kominsky Method', type: 'series', genre: 'comedy', rating: 8.2, year: 2018, seasons: 3, episodes: 22, description: 'An aging actor who long ago enjoyed a brush with fame makes his living as an acting coach.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 1100000 },
  { id: 23, title: 'Dead to Me', type: 'series', genre: 'comedy', rating: 8.0, year: 2019, seasons: 3, episodes: 30, description: 'A series about a powerful friendship that blossoms between a tightly wound widow and a free spirit with a shocking secret.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 1250000 },
  { id: 24, title: 'Grace and Frankie', type: 'series', genre: 'comedy', rating: 8.2, year: 2015, seasons: 7, episodes: 94, description: 'Finding out that their husbands are not just work partners, but have also been romantically involved for the last twenty years, two women with an already strained relationship try to cope with the circumstances together.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1550000 },
  { id: 25, title: 'Russian Doll', type: 'series', genre: 'comedy', rating: 7.8, year: 2019, seasons: 2, episodes: 15, description: 'A cynical young woman in New York City keeps dying and returning to the party that\'s being thrown in her honor on that same evening.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 77, viewingHours: 1050000 },

  // Comedy Movies
  { id: 26, title: 'Don\'t Look Up', type: 'movie', genre: 'comedy', rating: 7.2, year: 2021, runtime: 138, description: 'Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1200000 },
  { id: 27, title: 'The Kissing Booth', type: 'movie', genre: 'comedy', rating: 6.0, year: 2018, runtime: 105, description: 'A high school student is forced to confront a secret crush when she volunteers to work at a kissing booth.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 720000 },
  { id: 28, title: 'Murder Mystery', type: 'movie', genre: 'comedy', rating: 6.0, year: 2019, runtime: 97, description: 'A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 890000 },
  { id: 29, title: 'The Wrong Missy', type: 'movie', genre: 'comedy', rating: 5.7, year: 2020, runtime: 90, description: 'Tim thinks he\'s invited the woman of his dreams on a work retreat to Hawaii, realizing too late he mistakenly texted someone from a nightmare blind date.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 72, viewingHours: 650000 },
  { id: 30, title: 'Hubie Halloween', type: 'movie', genre: 'comedy', rating: 5.2, year: 2020, runtime: 102, description: 'Despite his devotion to his hometown of Salem, Hubie Dubois is a figure of mockery for kids and adults alike. But this year, something is going bump in the night, and it\'s up to Hubie to save Halloween.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 69, viewingHours: 580000 },

  // Drama Series
  { id: 31, title: 'The Crown', type: 'series', genre: 'drama', rating: 8.7, year: 2016, seasons: 6, episodes: 60, description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 90, viewingHours: 2200000 },
  { id: 32, title: 'House of Cards', type: 'series', genre: 'drama', rating: 8.7, year: 2013, seasons: 6, episodes: 73, description: 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 85, viewingHours: 1700000 },
  { id: 33, title: 'Orange Is the New Black', type: 'series', genre: 'drama', rating: 8.1, year: 2013, seasons: 7, episodes: 91, description: 'A privileged New Yorker ends up in a women\'s prison when a past crime catches up with her in this Emmy-winning series.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 88, viewingHours: 1950000 },
  { id: 34, title: 'Bridgerton', type: 'series', genre: 'drama', rating: 7.3, year: 2020, seasons: 2, episodes: 16, description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 94, viewingHours: 2300000 },
  { id: 35, title: 'The Queen\'s Gambit', type: 'series', genre: 'drama', rating: 8.5, year: 2020, seasons: 1, episodes: 7, description: 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 93, viewingHours: 2150000 },
  { id: 36, title: 'When They See Us', type: 'series', genre: 'drama', rating: 8.9, year: 2019, seasons: 1, episodes: 4, description: 'Five teens from Harlem become trapped in a nightmare when they\'re falsely accused of a brutal attack in Central Park.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 86, viewingHours: 1450000 },
  { id: 37, title: 'Unorthodox', type: 'series', genre: 'drama', rating: 8.2, year: 2020, seasons: 1, episodes: 4, description: 'A young woman flees her arranged marriage and religious community to start a new life abroad.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 1200000 },
  { id: 38, title: 'Maid', type: 'series', genre: 'drama', rating: 8.4, year: 2021, seasons: 1, episodes: 10, description: 'After fleeing an abusive relationship, a young mother finds a job cleaning houses as she fights to provide for her child and build them a better future.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1350000 },
  { id: 39, title: 'Virgin River', type: 'series', genre: 'drama', rating: 7.4, year: 2019, seasons: 4, episodes: 42, description: 'Seeking a fresh start, nurse practitioner Melinda Monroe moves from Los Angeles to a remote Northern California town and is surprised by what and who she finds.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1550000 },
  { id: 40, title: 'Ginny & Georgia', type: 'series', genre: 'drama', rating: 7.5, year: 2021, seasons: 2, episodes: 20, description: 'Free-spirited Georgia and her two kids, Ginny and Austin, move north in search of a fresh start but find that the road to new beginnings can be bumpy.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 1250000 },

  // Drama Movies
  { id: 41, title: 'Marriage Story', type: 'movie', genre: 'drama', rating: 7.9, year: 2019, runtime: 137, description: 'Noah Baumbach\'s incisive and compassionate look at a marriage breaking up and a family staying together.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 980000 },
  { id: 42, title: 'The Irishman', type: 'movie', genre: 'drama', rating: 7.8, year: 2019, runtime: 209, description: 'An aging hitman recalls his time with the mob and the intersections between his life and the Teamsters union leader Jimmy Hoffa.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1100000 },
  { id: 43, title: 'Roma', type: 'movie', genre: 'drama', rating: 7.7, year: 2018, runtime: 135, description: 'A year in the life of a middle-class family\'s maid in Mexico City in the early 1970s.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 850000 },
  { id: 44, title: 'The Two Popes', type: 'movie', genre: 'drama', rating: 7.6, year: 2019, runtime: 125, description: 'Behind Vatican walls, the conservative Pope Benedict XVI and the liberal future Pope Francis must find common ground to forge a new path for the Catholic Church.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 75, viewingHours: 780000 },
  { id: 45, title: 'Pieces of a Woman', type: 'movie', genre: 'drama', rating: 7.0, year: 2020, runtime: 126, description: 'When a young mother\'s home birth ends in unfathomable tragedy, she begins a year-long odyssey of mourning that fractures relationships with loved ones.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 72, viewingHours: 650000 },

  // Thriller Series
  { id: 46, title: 'Mindhunter', type: 'series', genre: 'thriller', rating: 8.6, year: 2017, seasons: 2, episodes: 19, description: 'In the late 1970s, two FBI agents broaden the realm of criminal science by investigating the psychology behind murder.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 88, viewingHours: 1650000 },
  { id: 47, title: 'You', type: 'series', genre: 'thriller', rating: 7.7, year: 2018, seasons: 4, episodes: 40, description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1450000 },
  { id: 48, title: 'Dark', type: 'series', genre: 'thriller', rating: 8.8, year: 2017, seasons: 3, episodes: 26, description: 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 91, viewingHours: 1900000 },
  { id: 49, title: 'The Sinner', type: 'series', genre: 'thriller', rating: 7.9, year: 2017, seasons: 4, episodes: 32, description: 'Anthology series that examines how and why ordinary people commit brutal crimes.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 1350000 },
  { id: 50, title: 'Safe', type: 'series', genre: 'thriller', rating: 7.2, year: 2018, seasons: 1, episodes: 8, description: 'After his teenage daughter goes missing, a desperate father tries to find her by following the clues she left behind.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 950000 },
  { id: 51, title: 'Elite', type: 'series', genre: 'thriller', rating: 7.5, year: 2018, seasons: 6, episodes: 56, description: 'When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 85, viewingHours: 1550000 },
  { id: 52, title: 'The Stranger', type: 'series', genre: 'thriller', rating: 7.3, year: 2020, seasons: 1, episodes: 8, description: 'A web of secrets sends family man Adam Price on a desperate quest to uncover the truth about the people closest to him.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 1100000 },
  { id: 53, title: 'Clickbait', type: 'series', genre: 'thriller', rating: 7.2, year: 2021, seasons: 1, episodes: 8, description: 'When family man Nick Brewer is abducted in a crime with a sinister online twist, those closest to him race to uncover who is behind it and why.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 1200000 },
  { id: 54, title: 'Bodyguard', type: 'series', genre: 'thriller', rating: 8.0, year: 2018, seasons: 1, episodes: 6, description: 'A troubled war veteran is assigned to protect a controversial politician who may be the target of a terror plot.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 1250000 },
  { id: 55, title: 'Dirty John', type: 'series', genre: 'thriller', rating: 7.2, year: 2018, seasons: 2, episodes: 16, description: 'Anthology series in which each season is based on a true crime story featuring an epic tale of love gone wrong.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 74, viewingHours: 980000 },

  // Thriller Movies
  { id: 56, title: 'Bird Box', type: 'movie', genre: 'thriller', rating: 6.6, year: 2018, runtime: 124, description: 'Five years after an ominous unseen presence drives most of society to suicide, a mother and her two children make a desperate bid to reach safety.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 87, viewingHours: 1300000 },
  { id: 57, title: 'The Platform', type: 'movie', genre: 'thriller', rating: 7.0, year: 2019, runtime: 94, description: 'A vertical prison with one cell per level. Two people per cell. Only one food platform and two minutes per day to feed. An endless nightmare trapped in The Hole.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 850000 },
  { id: 58, title: 'Cam', type: 'movie', genre: 'thriller', rating: 5.9, year: 2018, runtime: 94, description: 'Alice, an ambitious camgirl, wakes up one day to discover she\'s been replaced on her show with an exact replica of herself.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 71, viewingHours: 620000 },
  { id: 59, title: 'In the Tall Grass', type: 'movie', genre: 'thriller', rating: 5.4, year: 2019, runtime: 101, description: 'After hearing a young boy\'s cry for help, a sister and brother venture into a vast field of tall grass to rescue him, but soon discover there may be no way out.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 68, viewingHours: 580000 },
  { id: 60, title: 'Fractured', type: 'movie', genre: 'thriller', rating: 6.4, year: 2019, runtime: 99, description: 'A man searches for his missing wife and daughter in a hospital, but it is revealed that they were never there to begin with.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 73, viewingHours: 720000 },

  // Documentary Series
  { id: 61, title: 'Making a Murderer', type: 'series', genre: 'documentary', rating: 8.6, year: 2015, seasons: 2, episodes: 20, description: 'Filmed over 10 years, this real-life thriller follows a DNA exoneree who, while exposing police corruption, becomes a suspect in a grisly new crime.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 89, viewingHours: 1750000 },
  { id: 62, title: 'Tiger King', type: 'series', genre: 'documentary', rating: 7.5, year: 2020, seasons: 2, episodes: 12, description: 'A rivalry between big cat eccentrics takes a dark turn when one of them is accused of hiring a hitman to kill her nemesis.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 93, viewingHours: 2050000 },
  { id: 63, title: 'Wild Wild Country', type: 'series', genre: 'documentary', rating: 8.2, year: 2018, seasons: 1, episodes: 6, description: 'When a controversial guru builds a utopian city in the Oregon desert, it causes a massive conflict with local ranchers. This docuseries reveals how it all went wrong.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 80, viewingHours: 1050000 },
  { id: 64, title: 'The Keepers', type: 'series', genre: 'documentary', rating: 8.1, year: 2017, seasons: 1, episodes: 7, description: 'A nun\'s murder in Baltimore kicks off a sprawling investigation into a web of secrets that may have been covered up for decades.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 77, viewingHours: 980000 },
  { id: 65, title: 'Don\'t F**k with Cats', type: 'series', genre: 'documentary', rating: 8.0, year: 2019, seasons: 1, episodes: 3, description: 'A group of online justice seekers track down a man who posted a video of himself killing kittens.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1200000 },
  { id: 66, title: 'The Staircase', type: 'series', genre: 'documentary', rating: 8.2, year: 2018, seasons: 1, episodes: 13, description: 'Academy Award-winning documentary filmmaker Jean-Xavier de Lestrade presents a gripping courtroom thriller, offering a rare and revealing inside look at a high-profile murder trial.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 1150000 },
  { id: 67, title: 'Evil Genius', type: 'series', genre: 'documentary', rating: 7.5, year: 2018, seasons: 1, episodes: 4, description: 'This baffling true crime story starts with the grisly death of a pizza man who robs a bank with a bomb around his neck - and gets weirder from there.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 75, viewingHours: 850000 },
  { id: 68, title: 'The Disappearance of Madeleine McCann', type: 'series', genre: 'documentary', rating: 6.6, year: 2019, seasons: 1, episodes: 8, description: 'The documentary takes a detailed look at the disappearance of 3-year-old Madeleine McCann, who vanished from the seaside resort of Praia da Luz in Portugal, while on holiday with her family.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 73, viewingHours: 920000 },
  { id: 69, title: 'Conversations with a Killer: The Ted Bundy Tapes', type: 'series', genre: 'documentary', rating: 7.7, year: 2019, seasons: 1, episodes: 4, description: 'A look inside the mind of serial killer Ted Bundy, featuring interviews with him on death row.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 1100000 },
  { id: 70, title: 'American Factory', type: 'series', genre: 'documentary', rating: 7.4, year: 2019, seasons: 1, episodes: 1, description: 'In post-industrial Ohio, a Chinese billionaire opens a new factory in the husk of an abandoned General Motors plant, hiring two thousand blue-collar Americans.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 780000 },

  // Documentary Movies
  { id: 71, title: 'My Octopus Teacher', type: 'movie', genre: 'documentary', rating: 8.1, year: 2020, runtime: 85, description: 'A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 920000 },
  { id: 72, title: 'The Social Dilemma', type: 'movie', genre: 'documentary', rating: 7.6, year: 2020, runtime: 94, description: 'Explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 86, viewingHours: 1150000 },
  { id: 73, title: 'Icarus', type: 'movie', genre: 'documentary', rating: 7.9, year: 2017, runtime: 121, description: 'When filmmaker Bryan Fogel sets out to uncover the truth about doping in sports, a chance meeting with a Russian scientist transforms his story from a personal experiment into a geopolitical thriller.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 850000 },
  { id: 74, title: 'Fyre: The Greatest Party That Never Happened', type: 'movie', genre: 'documentary', rating: 7.2, year: 2019, runtime: 97, description: 'An exclusive behind the scenes look at the infamous unraveling of the Fyre music festival.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 80, viewingHours: 950000 },
  { id: 75, title: 'What the Health', type: 'movie', genre: 'documentary', rating: 7.1, year: 2017, runtime: 97, description: 'An intrepid filmmaker on a journey of discovery as he uncovers possibly the largest health cover-up of our time.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 74, viewingHours: 720000 },

  // Romance Series
  { id: 76, title: 'Bridgerton', type: 'series', genre: 'romance', rating: 7.3, year: 2020, seasons: 2, episodes: 16, description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 94, viewingHours: 2300000 },
  { id: 77, title: 'Virgin River', type: 'series', genre: 'romance', rating: 7.4, year: 2019, seasons: 4, episodes: 42, description: 'Seeking a fresh start, nurse practitioner Melinda Monroe moves from Los Angeles to a remote Northern California town and is surprised by what and who she finds.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1550000 },
  { id: 78, title: 'Sweet Magnolias', type: 'series', genre: 'romance', rating: 7.3, year: 2020, seasons: 2, episodes: 20, description: 'Lifelong friends Maddie, Helen and Dana Sue lift each other up as they juggle relationships, family and careers in the small, Southern town of Serenity.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 1250000 },
  { id: 79, title: 'Dash & Lily', type: 'series', genre: 'romance', rating: 7.4, year: 2020, seasons: 1, episodes: 8, description: 'A whirlwind holiday romance builds as cynical Dash and optimistic Lily trade dares, dreams and desires in the notebook they pass back and forth at locations around New York City.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 950000 },
  { id: 80, title: 'Love is Blind', type: 'series', genre: 'romance', rating: 6.3, year: 2020, seasons: 3, episodes: 30, description: 'Singles who want to be loved for who they are, rather than what they look like, have signed up for a less conventional approach to modern dating.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 1350000 },

  // Romance Movies
  { id: 81, title: 'To All the Boys I\'ve Loved Before', type: 'movie', genre: 'romance', rating: 7.0, year: 2018, runtime: 99, description: 'A teenage girl\'s secret love letters are exposed and wreak havoc on her love life.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 85, viewingHours: 1200000 },
  { id: 82, title: 'The Half of It', type: 'movie', genre: 'romance', rating: 6.9, year: 2020, runtime: 104, description: 'A shy student helps the sweet jock woo the girl they both like.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 77, viewingHours: 780000 },
  { id: 83, title: 'Always Be My Maybe', type: 'movie', genre: 'romance', rating: 6.8, year: 2019, runtime: 101, description: 'Everyone assumed Sasha and Marcus would wind up together except for Sasha and Marcus. Reconnecting after 15 years, the two start to wonder--maybe?', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 890000 },
  { id: 84, title: 'Set It Up', type: 'movie', genre: 'romance', rating: 6.5, year: 2018, runtime: 105, description: 'Two corporate executive assistants hatch a plan to match-make their two bosses.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 74, viewingHours: 720000 },
  { id: 85, title: 'The Perfect Date', type: 'movie', genre: 'romance', rating: 5.8, year: 2019, runtime: 89, description: 'To save up for college, Brooks Rattigan creates an app where anyone can pay him to play the perfect stand-in boyfriend for any occasion.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 71, viewingHours: 650000 },

  // Horror Series
  { id: 86, title: 'The Haunting of Hill House', type: 'series', genre: 'horror', rating: 8.6, year: 2018, seasons: 1, episodes: 10, description: 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 87, viewingHours: 1650000 },
  { id: 87, title: 'Midnight Mass', type: 'series', genre: 'horror', rating: 7.7, year: 2021, seasons: 1, episodes: 7, description: 'An isolated island community experiences miraculous events - and frightening omens - after the arrival of a charismatic, mysterious young priest.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 79, viewingHours: 950000 },
  { id: 88, title: 'The Haunting of Bly Manor', type: 'series', genre: 'horror', rating: 7.4, year: 2020, seasons: 1, episodes: 9, description: 'After an au pair\'s tragic death, Henry hires a young American nanny to care for his orphaned niece and nephew who reside at Bly Manor with the chef Owen, groundskeeper Jamie and housekeeper, Mrs. Grose.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 81, viewingHours: 1150000 },
  { id: 89, title: 'Ratched', type: 'series', genre: 'horror', rating: 7.2, year: 2020, seasons: 2, episodes: 18, description: 'In 1947, Mildred Ratched begins working as a nurse at a leading psychiatric hospital. But beneath her stylish exterior lurks a growing darkness.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 1050000 },
  { id: 90, title: 'Brand New Cherry Flavor', type: 'series', genre: 'horror', rating: 6.8, year: 2021, seasons: 1, episodes: 8, description: 'A filmmaker heads to Hollywood in the early \'90s to make her movie but tumbles down a hallucinatory rabbit hole of sex, magic, revenge - and kittens.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 72, viewingHours: 850000 },

  // Horror Movies
  { id: 91, title: 'His House', type: 'movie', genre: 'horror', rating: 6.5, year: 2020, runtime: 93, description: 'A refugee couple makes a harrowing escape from war-torn South Sudan, but then they struggle to adjust to their new life in an English town that has an evil lurking beneath the surface.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 74, viewingHours: 680000 },
  { id: 92, title: 'Fear Street Trilogy', type: 'movie', genre: 'horror', rating: 6.7, year: 2021, runtime: 107, description: 'A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 1100000 },
  { id: 93, title: 'The Ritual', type: 'movie', genre: 'horror', rating: 6.3, year: 2017, runtime: 94, description: 'A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods that\'s stalking them.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 71, viewingHours: 620000 },
  { id: 94, title: 'Cam', type: 'movie', genre: 'horror', rating: 5.9, year: 2018, runtime: 94, description: 'Alice, an ambitious camgirl, wakes up one day to discover she\'s been replaced on her show with an exact replica of herself.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 69, viewingHours: 580000 },
  { id: 95, title: 'Velvet Buzzsaw', type: 'movie', genre: 'horror', rating: 5.7, year: 2019, runtime: 113, description: 'A supernatural thriller set in the contemporary art world scene of Los Angeles, where big money artists and mega-collectors pay a high price for passion.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 67, viewingHours: 520000 },

  // Sci-Fi Series
  { id: 96, title: 'Black Mirror', type: 'series', genre: 'sci-fi', rating: 8.8, year: 2011, seasons: 6, episodes: 27, description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 92, viewingHours: 2100000 },
  { id: 97, title: 'Lost in Space', type: 'series', genre: 'sci-fi', rating: 7.3, year: 2018, seasons: 3, episodes: 28, description: 'After crash-landing on an alien planet, the Robinson family fight against all odds to survive and escape, but they\'re surrounded by hidden dangers.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 80, viewingHours: 1350000 },
  { id: 98, title: 'Altered Carbon', type: 'series', genre: 'sci-fi', rating: 8.0, year: 2018, seasons: 2, episodes: 18, description: 'More than 300 years in the future, society has been transformed by new technology, leading to human bodies being interchangeable and death no longer being permanent.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1450000 },
  { id: 99, title: 'The OA', type: 'series', genre: 'sci-fi', rating: 7.8, year: 2016, seasons: 2, episodes: 16, description: 'Seven years after vanishing from her home, a young woman returns with mysterious new abilities and recruits five strangers for a secret mission.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 1050000 },
  { id: 100, title: 'Another Life', type: 'series', genre: 'sci-fi', rating: 5.2, year: 2019, seasons: 2, episodes: 20, description: 'After a massive alien artifact lands on Earth, Niko Breckinridge leads an interstellar mission to track down its source and make first contact.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 68, viewingHours: 750000 },

  // Sci-Fi Movies
  { id: 101, title: 'The Midnight Sky', type: 'movie', genre: 'sci-fi', rating: 5.7, year: 2020, runtime: 118, description: 'A lonely scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 73, viewingHours: 750000 },
  { id: 102, title: 'Stowaway', type: 'movie', genre: 'sci-fi', rating: 5.6, year: 2021, runtime: 116, description: 'A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 69, viewingHours: 580000 },
  { id: 103, title: 'I Am Mother', type: 'movie', genre: 'sci-fi', rating: 6.7, year: 2019, runtime: 113, description: 'A teenage girl is raised underground by a robot "Mother", designed to repopulate the earth following an extinction event.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 72, viewingHours: 680000 },
  { id: 104, title: 'Oxygen', type: 'movie', genre: 'sci-fi', rating: 6.5, year: 2021, runtime: 100, description: 'A woman wakes up in a cryogenic pod with no memory of how she got there, and must find a way out before running out of air.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 70, viewingHours: 620000 },
  { id: 105, title: 'The Cloverfield Paradox', type: 'movie', genre: 'sci-fi', rating: 5.5, year: 2018, runtime: 102, description: 'Orbiting Earth in an experimental space station, a team of scientists find themselves isolated when the planet vanishes beneath them.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 66, viewingHours: 550000 },

  // Animation Series
  { id: 106, title: 'BoJack Horseman', type: 'series', genre: 'animation', rating: 8.8, year: 2014, seasons: 6, episodes: 77, description: 'Meet the most beloved sitcom horse of the \'90s, 20 years later. He\'s a curmudgeon with a heart of... not quite gold... but something like gold.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 89, viewingHours: 1800000 },
  { id: 107, title: 'Big Mouth', type: 'series', genre: 'animation', rating: 7.8, year: 2017, seasons: 6, episodes: 61, description: 'Teenage friends find their lives upended by the wonders and horrors of puberty in this edgy comedy from real-life pals Nick Kroll and Andrew Goldberg.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 82, viewingHours: 1500000 },
  { id: 108, title: 'Castlevania', type: 'series', genre: 'animation', rating: 8.3, year: 2017, seasons: 4, episodes: 32, description: 'A vampire hunter fights to save a besieged city from an army of otherworldly creatures controlled by Dracula.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 87, viewingHours: 1650000 },
  { id: 109, title: 'F is for Family', type: 'series', genre: 'animation', rating: 8.0, year: 2015, seasons: 5, episodes: 44, description: 'Follow the Murphy family back to the 1970s, when kids roamed wild, beer flowed freely and nothing came between a man and his TV.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 78, viewingHours: 1200000 },
  { id: 110, title: 'Disenchantment', type: 'series', genre: 'animation', rating: 7.2, year: 2018, seasons: 4, episodes: 40, description: 'Princess Tiabeanie, \'Bean\', is annoyed at her imminent arranged marriage to Prince Merkimer. Then she meets Luci, a demon, and Elfo, an elf, and things get rather exciting, and dangerous.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 75, viewingHours: 1050000 },

  // Animation Movies
  { id: 111, title: 'Klaus', type: 'movie', genre: 'animation', rating: 8.2, year: 2019, runtime: 96, description: 'A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg\'s new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 86, viewingHours: 1250000 },
  { id: 112, title: 'The Mitchells vs. The Machines', type: 'movie', genre: 'animation', rating: 7.6, year: 2021, runtime: 113, description: 'A quirky, dysfunctional family\'s road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity\'s unlikeliest last hope.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 84, viewingHours: 1180000 },
  { id: 113, title: 'Over the Moon', type: 'movie', genre: 'animation', rating: 6.3, year: 2020, runtime: 95, description: 'Fueled by memories of her late mother, 13-year-old Fei Fei builds a rocket ship to the moon to prove the existence of a legendary Moon Goddess.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 76, viewingHours: 850000 },
  { id: 114, title: 'The Willoughbys', type: 'movie', genre: 'animation', rating: 6.4, year: 2020, runtime: 90, description: 'Convinced they\'d be better off raising themselves, the Willoughby children hatch a sneaky plan to send their selfish parents on vacation.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 73, viewingHours: 720000 },
  { id: 115, title: 'Next Gen', type: 'movie', genre: 'animation', rating: 6.6, year: 2018, runtime: 106, description: 'A friendship with a top-secret robot turns a lonely girl\'s life into a thrilling adventure as they take on bullies, evil bots and a scheming madman.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 71, viewingHours: 680000 },

  // Additional Popular Content
  { id: 116, title: 'Wednesday', type: 'series', genre: 'horror', rating: 8.1, year: 2022, seasons: 1, episodes: 8, description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 96, viewingHours: 2500000 },
  { id: 117, title: 'Dahmer – Monster: The Jeffrey Dahmer Story', type: 'series', genre: 'thriller', rating: 8.2, year: 2022, seasons: 1, episodes: 10, description: 'The story of one of America\'s most notorious serial killers, largely told from the point of view of his victims.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 94, viewingHours: 2400000 },
  { id: 118, title: 'All Quiet on the Western Front', type: 'movie', genre: 'drama', rating: 7.8, year: 2022, runtime: 148, description: 'A young German soldier\'s terrifying experiences and distress on the western front during World War I.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 85, viewingHours: 1350000 },
  { id: 119, title: 'Glass Onion: A Knives Out Mystery', type: 'movie', genre: 'thriller', rating: 7.2, year: 2022, runtime: 139, description: 'Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island. When someone turns up dead, Detective Benoit Blanc is put on the case.', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 88, viewingHours: 1650000 },
  { id: 120, title: 'The Watcher', type: 'series', genre: 'thriller', rating: 7.0, year: 2022, seasons: 1, episodes: 7, description: 'A married couple moves into their dream house, but very quickly the dream becomes a nightmare when they receive threatening letters from someone called "The Watcher."', image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400', popularity: 83, viewingHours: 1450000 }
];

export class ContentManager {
  constructor() {
    this.allContent = [...netflixContent];
    this.filteredContent = [...netflixContent];
    this.currentGenre = 'all';
    this.currentSearchTerm = '';
    this.currentSortBy = 'title';
  }

  filterContent(searchTerm = '', genre = 'all', sortBy = 'title') {
    this.currentSearchTerm = searchTerm.toLowerCase();
    this.currentGenre = genre;
    this.currentSortBy = sortBy;

    let filtered = this.allContent.filter(content => {
      const matchesSearch = content.title.toLowerCase().includes(this.currentSearchTerm) ||
                           content.description.toLowerCase().includes(this.currentSearchTerm);
      const matchesGenre = genre === 'all' || content.genre === genre;
      
      return matchesSearch && matchesGenre;
    });

    // Sort content
    filtered = this.sortContent(filtered, sortBy);
    
    this.filteredContent = filtered;
    return filtered;
  }

  sortContent(content, sortBy) {
    const sorted = [...content];
    
    switch (sortBy) {
      case 'rating-low':
        return sorted.sort((a, b) => a.rating - b.rating);
      case 'rating-high':
        return sorted.sort((a, b) => b.rating - a.rating);
      case 'year':
        return sorted.sort((a, b) => b.year - a.year);
      case 'popularity':
        return sorted.sort((a, b) => b.popularity - a.popularity);
      case 'title':
      default:
        return sorted.sort((a, b) => a.title.localeCompare(b.title));
    }
  }

  highlightSearchTerm(text, searchTerm) {
    if (!searchTerm) return text;
    
    const regex = new RegExp(`(${searchTerm})`, 'gi');
    return text.replace(regex, '<span class="highlight">$1</span>');
  }

  getFilteredContent() {
    return this.filteredContent;
  }

  getContentCount() {
    return this.filteredContent.length;
  }

  getTotalContentCount() {
    return this.allContent.length;
  }
}