// Netflix content data and management
export const contentGenres = [
  { id: 'all', name: 'All Content', icon: 'fas fa-th' },
  { id: 'action', name: 'Action', icon: 'fas fa-fist-raised' },
  { id: 'comedy', name: 'Comedy', icon: 'fas fa-laugh' },
  { id: 'drama', name: 'Drama', icon: 'fas fa-theater-masks' },
  { id: 'thriller', name: 'Thriller', icon: 'fas fa-eye' },
  { id: 'documentary', name: 'Documentary', icon: 'fas fa-video' },
  { id: 'romance', name: 'Romance', icon: 'fas fa-heart' },
  { id: 'horror', name: 'Horror', icon: 'fas fa-ghost' },
  { id: 'sci-fi', name: 'Sci-Fi', icon: 'fas fa-rocket' },
  { id: 'animation', name: 'Animation', icon: 'fas fa-palette' }
];

export const netflixContent = [
  // Action
  { 
    id: 1, 
    title: 'Stranger Things', 
    type: 'series', 
    genre: 'action', 
    rating: 8.7, 
    year: 2016, 
    seasons: 4, 
    episodes: 42, 
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.', 
    image: 'https://m.media-amazon.com/images/M/MV5BN2ZmYjg1YmItNWQ4OC00YWM0LWE0ZDktYThjOTZiZjhhN2Q2XkEyXkFqcGdeQXVyNjgxNTQ3Mjk@._V1_FMjpg_UX1000_.jpg', 
    popularity: 95, 
    viewingHours: 2400000 
  },
  { 
    id: 2, 
    title: 'The Witcher', 
    type: 'series', 
    genre: 'action', 
    rating: 8.2, 
    year: 2019, 
    seasons: 3, 
    episodes: 24, 
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 
    image: 'https://m.media-amazon.com/images/M/MV5BOGE4MmVjMDgtMzIzYy00NjEwLWJlODMtMDI1MGY2ZDlhMzE2XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1800000 
  },
  { 
    id: 3, 
    title: 'Extraction', 
    type: 'movie', 
    genre: 'action', 
    rating: 6.8, 
    year: 2020, 
    runtime: 116, 
    description: 'A black-market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMzZkYTJmYmYtYmM3ZC00OGY1LWI4YTgtNzc5MzE2ODEzMGE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 950000 
  },
  { 
    id: 4, 
    title: 'Money Heist', 
    type: 'series', 
    genre: 'action', 
    rating: 8.3, 
    year: 2017, 
    seasons: 5, 
    episodes: 41, 
    description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', 
    image: 'https://m.media-amazon.com/images/M/MV5BODI0ZTljYTMtODQ1NC00NmI0LTk1YWUtN2FlNDM1MDExMDlhXkEyXkFqcGdeQXVyMTM0NTUzNDIy@._V1_FMjpg_UX1000_.jpg', 
    popularity: 91, 
    viewingHours: 2100000 
  },
  { 
    id: 5, 
    title: 'Red Notice', 
    type: 'movie', 
    genre: 'action', 
    rating: 6.4, 
    year: 2021, 
    runtime: 118, 
    description: 'An Interpol agent tracks the world\'s most wanted art thief.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZmRjODgyMzEtMzIxYS00OWY2LTk4YjUtMGMzZjMzMTZiN2Q0XkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 890000 
  },
  { 
    id: 6, 
    title: 'Cobra Kai', 
    type: 'series', 
    genre: 'action', 
    rating: 8.5, 
    year: 2018, 
    seasons: 6, 
    episodes: 60, 
    description: 'Decades after the tournament that changed their lives, the rivalry between Johnny and Daniel reignites in this sequel to the Karate Kid films.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1750000 
  },
  { 
    id: 7, 
    title: 'The Old Guard', 
    type: 'movie', 
    genre: 'action', 
    rating: 6.7, 
    year: 2020, 
    runtime: 125, 
    description: 'A covert team of immortal mercenaries is suddenly exposed and must now fight to keep their identity a secret.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjFhZjM4ZGEtYWFmZC00NmUzLWJkODAtYjE3MjA3ZjkzN2Y4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1200000 
  },
  { 
    id: 8, 
    title: 'Lupin', 
    type: 'series', 
    genre: 'action', 
    rating: 7.5, 
    year: 2021, 
    seasons: 3, 
    episodes: 17, 
    description: 'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZjEyYTgwYzAtMjNiOS00ZjNhLWE3ZWEtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1450000 
  },
  { 
    id: 9, 
    title: 'Army of the Dead', 
    type: 'movie', 
    genre: 'action', 
    rating: 5.8, 
    year: 2021, 
    runtime: 148, 
    description: 'Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU0MGI2MmQtZmNlNy00MzJlLTlkODQtNTc3ZGJlMzBkMzUyXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 76, 
    viewingHours: 980000 
  },
  { 
    id: 10, 
    title: 'Sweet Tooth', 
    type: 'series', 
    genre: 'action', 
    rating: 7.8, 
    year: 2021, 
    seasons: 3, 
    episodes: 24, 
    description: 'On a perilous adventure across a post-apocalyptic world, a lovable boy who\'s half-human and half-deer searches for a new beginning with a gruff protector.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjk1Njk3YjctMmMyYS00Y2I4LWE4NDYtMzUxYzJkMGE2NTgwXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1350000 
  },
  { 
    id: 11, 
    title: 'Ozark', 
    type: 'series', 
    genre: 'action', 
    rating: 8.4, 
    year: 2017, 
    seasons: 4, 
    episodes: 44, 
    description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNDUyNjcwNDc0N15BMl5BanBnXkFtZTgwNTMwMjkxNzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1850000 
  },
  { 
    id: 12, 
    title: 'The Umbrella Academy', 
    type: 'series', 
    genre: 'action', 
    rating: 7.9, 
    year: 2019, 
    seasons: 4, 
    episodes: 36, 
    description: 'A dysfunctional family of superheroes comes together to solve the mystery of their father\'s death, the threat of the apocalypse and more.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYTU5ZThjNzEtMjQ1Zi00ZWUwLWFmMDEtODEzZjUzMWE0NTNjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1650000 
  },
  { 
    id: 13, 
    title: 'Squid Game', 
    type: 'series', 
    genre: 'action', 
    rating: 8.0, 
    year: 2021, 
    seasons: 2, 
    episodes: 17, 
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games for a tempting prize, but the stakes are deadly.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 96, 
    viewingHours: 2800000 
  },
  { 
    id: 14, 
    title: 'Vikings: Valhalla', 
    type: 'series', 
    genre: 'action', 
    rating: 7.2, 
    year: 2022, 
    seasons: 3, 
    episodes: 24, 
    description: 'In this sequel to Vikings, a hundred years have passed and a new generation of legendary heroes arises to forge their own destiny.', 
    image: 'https://m.media-amazon.com/images/M/MV5BM2ZhZjM0NWUtYTFmYy00Zjk1LWE4YjQtNzJlZGJkMGJmOTg2XkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 1250000 
  },
  { 
    id: 15, 
    title: 'The Gray Man', 
    type: 'movie', 
    genre: 'action', 
    rating: 6.5, 
    year: 2022, 
    runtime: 129, 
    description: 'When the CIA\'s most skilled mercenary known as Court Gentry, aka Sierra Six, accidentally uncovers dark agency secrets, he becomes a primary target.', 
    image: 'https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 1050000 
  },

  // Comedy
  { 
    id: 16, 
    title: 'The Good Place', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.2, 
    year: 2016, 
    seasons: 4, 
    episodes: 50, 
    description: 'A woman struggles to be a good person when she realizes she\'s been mistakenly sent to the Good Place instead of the Bad Place.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMzRkNWE0YzEtYzU0YS00MzIxLWI4N2UtYjY3ZjBlZDQyMzI2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1600000 
  },
  { 
    id: 17, 
    title: 'Brooklyn Nine-Nine', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.4, 
    year: 2013, 
    seasons: 8, 
    episodes: 153, 
    description: 'Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNzVkYWY4NzYtMWFlZi00YzkwLThhZDItZjcxYTU4ZTMzMDZmXkEyXkFqcGdeQXVyODA1NjQ0OTY@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1750000 
  },
  { 
    id: 18, 
    title: 'Don\'t Look Up', 
    type: 'movie', 
    genre: 'comedy', 
    rating: 7.2, 
    year: 2021, 
    runtime: 138, 
    description: 'Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNzMzNDg1NTEtOWNkOC00YjVmLTgyN2YtZmZhY2Q3NjY3YzNkXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1200000 
  },
  { 
    id: 19, 
    title: 'Schitt\'s Creek', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.5, 
    year: 2015, 
    seasons: 6, 
    episodes: 80, 
    description: 'When a wealthy family suddenly finds themselves broke, they are forced to leave their pampered lives to regroup in Schitt\'s Creek.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNDg1NTU2OWEtM2UzYi00Y2U0LWJmMWEtOWRhODVkMTJjNGRiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 92, 
    viewingHours: 1950000 
  },
  { 
    id: 20, 
    title: 'The Kissing Booth', 
    type: 'movie', 
    genre: 'comedy', 
    rating: 6.0, 
    year: 2018, 
    runtime: 105, 
    description: 'A high school student is forced to confront her secret crush at a kissing booth.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjQ4NzcxMjktYjI5Yi00NGY0LWI4NWYtZDI2NzVlYjU4NmY0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 76, 
    viewingHours: 720000 
  },
  { 
    id: 21, 
    title: 'Space Force', 
    type: 'series', 
    genre: 'comedy', 
    rating: 6.7, 
    year: 2020, 
    seasons: 2, 
    episodes: 17, 
    description: 'A four-star general begrudgingly teams up with an eccentric scientist to get the U.S. military\'s newest agency — Space Force — ready for lift-off.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMDljMjEzNDQtOGY3OS00OTM1LWJiMjYtZGQyMjg2ZjVkOGY2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 73, 
    viewingHours: 890000 
  },
  { 
    id: 22, 
    title: 'Emily in Paris', 
    type: 'series', 
    genre: 'comedy', 
    rating: 6.8, 
    year: 2020, 
    seasons: 4, 
    episodes: 40, 
    description: 'After landing her dream job in Paris, Chicago marketing exec Emily Cooper embraces her adventurous new life while juggling work, friends and romance.', 
    image: 'https://m.media-amazon.com/images/M/MV5BODc4YmE0NWItYzBhZC00YzY0LThlNWItZDRjMDExMzQ1MjdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 1400000 
  },
  { 
    id: 23, 
    title: 'Never Have I Ever', 
    type: 'series', 
    genre: 'comedy', 
    rating: 7.8, 
    year: 2020, 
    seasons: 4, 
    episodes: 40, 
    description: 'After a traumatic year, a first-generation Indian-American teenager wants to improve her status at school, but friends, family and feelings won\'t make it easy on her.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjZiNWRkYjQtZDI0Yi00ZTVkLWE5YjItZTNhNzAzOWVlNzJjXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 85, 
    viewingHours: 1300000 
  },
  { 
    id: 24, 
    title: 'The Politician', 
    type: 'series', 
    genre: 'comedy', 
    rating: 7.5, 
    year: 2019, 
    seasons: 2, 
    episodes: 15, 
    description: 'Payton Hobart, a student from Santa Barbara, has known since age seven that he\'s going to be President of the United States.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjEzMjA0ODk1NF5BMl5BanBnXkFtZTgwOTUyNzM3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 950000 
  },
  { 
    id: 25, 
    title: 'Dead to Me', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.0, 
    year: 2019, 
    seasons: 3, 
    episodes: 30, 
    description: 'A series about a powerful friendship that blossoms between a tightly wound widow and a free spirit with a shocking secret.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1150000 
  },
  { 
    id: 26, 
    title: 'Russian Doll', 
    type: 'series', 
    genre: 'comedy', 
    rating: 7.8, 
    year: 2019, 
    seasons: 2, 
    episodes: 15, 
    description: 'A cynical young woman in New York City keeps dying and returning to the party that\'s being thrown in her honor on that same evening.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYTcxMDgxNDMtZWM5Mi00MTUyLWI2NDYtZWRkNTQzMWI2NzVlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1050000 
  },
  { 
    id: 27, 
    title: 'The Umbrella Academy', 
    type: 'series', 
    genre: 'comedy', 
    rating: 7.9, 
    year: 2019, 
    seasons: 4, 
    episodes: 36, 
    description: 'A dysfunctional family of superheroes comes together to solve the mystery of their father\'s death, the threat of the apocalypse and more.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYTU5ZThjNzEtMjQ1Zi00ZWUwLWFmMDEtODEzZjUzMWE0NTNjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1650000 
  },
  { 
    id: 28, 
    title: 'Orange Is the New Black', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.1, 
    year: 2013, 
    seasons: 7, 
    episodes: 91, 
    description: 'A privileged New Yorker ends up in a women\'s prison when a past crime catches up with her in this Emmy-winning series.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjQzNjc1NzE5NF5BMl5BanBnXkFtZTgwNDMzNzQ2NDE@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 2200000 
  },
  { 
    id: 29, 
    title: 'Arrested Development', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.7, 
    year: 2003, 
    seasons: 5, 
    episodes: 84, 
    description: 'Level-headed son Michael Bluth takes over family affairs after his father is imprisoned. But the rest of his spoiled, dysfunctional family are making his job unbearable.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTQyNzE1Mjg0M15BMl5BanBnXkFtZTcwNjAyNjUyMw@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1450000 
  },
  { 
    id: 30, 
    title: 'Grace and Frankie', 
    type: 'series', 
    genre: 'comedy', 
    rating: 8.2, 
    year: 2015, 
    seasons: 7, 
    episodes: 94, 
    description: 'They\'re not friends, but when their husbands leave them for each other, proper Grace and eccentric Frankie begin to bond in this Emmy-nominated series.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTQwNjAzNDI0M15BMl5BanBnXkFtZTgwMTkxNzYxOTE@._V1_FMjpg_UX1000_.jpg', 
    popularity: 80, 
    viewingHours: 1750000 
  },

  // Drama
  { 
    id: 31, 
    title: 'The Crown', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.7, 
    year: 2016, 
    seasons: 6, 
    episodes: 60, 
    description: 'This drama follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZmY0MzBlNjctYjc4Ny00ODBmLTg1YTUtNzk4MDc3OGJhZjVlXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 90, 
    viewingHours: 2200000 
  },
  { 
    id: 32, 
    title: 'Ozark', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.4, 
    year: 2017, 
    seasons: 4, 
    episodes: 44, 
    description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNDUyNjcwNDc0N15BMl5BanBnXkFtZTgwNTMwMjkxNzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1850000 
  },
  { 
    id: 33, 
    title: 'Marriage Story', 
    type: 'movie', 
    genre: 'drama', 
    rating: 7.9, 
    year: 2019, 
    runtime: 137, 
    description: 'Noah Baumbach\'s incisive and compassionate look at a marriage breaking up and a family staying together.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMzc5YS00Y2E1LTgyNjAtY2Q3ZTE3NGY2OGFiXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 980000 
  },
  { 
    id: 34, 
    title: 'House of Cards', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.7, 
    year: 2013, 
    seasons: 6, 
    episodes: 73, 
    description: 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU5MzQ4MjkwNF5BMl5BanBnXkFtZTgwMzY4MjM3NDE@._V1_FMjpg_UX1000_.jpg', 
    popularity: 85, 
    viewingHours: 1700000 
  },
  { 
    id: 35, 
    title: 'The Irishman', 
    type: 'movie', 
    genre: 'drama', 
    rating: 7.8, 
    year: 2019, 
    runtime: 209, 
    description: 'An aging hitman recalls his time with the mob and the intersections between his life and the Teamsters union leader Jimmy Hoffa.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1100000 
  },
  { 
    id: 36, 
    title: 'When They See Us', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.9, 
    year: 2019, 
    seasons: 1, 
    episodes: 4, 
    description: 'Five teens from Harlem become trapped in a nightmare when they\'re falsely accused of a brutal attack in Central Park.', 
    image: 'https://m.media-amazon.com/images/M/MV5BZmJjYzMxYzAtNzMzZC00OTgxLWE4NzMtMWE0ZWZiOWYxNzFmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1350000 
  },
  { 
    id: 37, 
    title: 'Unbelievable', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.3, 
    year: 2019, 
    seasons: 1, 
    episodes: 8, 
    description: 'A teenager is charged with lying about having been raped, but two female detectives follow evidence that could reveal the truth.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjYwNDUyNTI3NV5BMl5BanBnXkFtZTgwNDg2MTgzNzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1150000 
  },
  { 
    id: 38, 
    title: 'The Queen\'s Gambit', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.5, 
    year: 2020, 
    seasons: 1, 
    episodes: 7, 
    description: 'In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.', 
    image: 'https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjM5ODk1NDU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 94, 
    viewingHours: 2100000 
  },
  { 
    id: 39, 
    title: 'Bridgerton', 
    type: 'series', 
    genre: 'drama', 
    rating: 7.3, 
    year: 2020, 
    seasons: 3, 
    episodes: 24, 
    description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 92, 
    viewingHours: 2300000 
  },
  { 
    id: 40, 
    title: 'Maid', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.4, 
    year: 2021, 
    seasons: 1, 
    episodes: 10, 
    description: 'After fleeing an abusive relationship, a young mother finds a job cleaning houses as she fights to provide for her child and build them a better future.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjE1ZDVhZjQtYjc2Yi00MzljLWE3NzMtNTcyNzY5NzE2NzJlXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1450000 
  },
  { 
    id: 41, 
    title: 'Inventing Anna', 
    type: 'series', 
    genre: 'drama', 
    rating: 6.9, 
    year: 2022, 
    seasons: 1, 
    episodes: 9, 
    description: 'A journalist with a lot to prove investigates the case of Anna Delvey, the Instagram-legendary German heiress who stole the hearts of New York\'s social scene.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 1200000 
  },
  { 
    id: 42, 
    title: 'The Watcher', 
    type: 'series', 
    genre: 'drama', 
    rating: 7.0, 
    year: 2022, 
    seasons: 1, 
    episodes: 7, 
    description: 'A married couple moves into their dream house, but very quickly the dream becomes a nightmare when they receive threatening letters from someone called "The Watcher."', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjY3NGE3NzYtMjlkNS00YjJmLTkwOTMtMzVjOWVkMTJjNGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1050000 
  },
  { 
    id: 43, 
    title: 'Dahmer', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.2, 
    year: 2022, 
    seasons: 1, 
    episodes: 10, 
    description: 'The story of one of America\'s most notorious serial killers, largely told from the point of view of his victims.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjY0NDYzMzctYjE2OS00YWNlLWE4NzItZmZhY2Q3NjY3YzNkXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 91, 
    viewingHours: 1850000 
  },
  { 
    id: 44, 
    title: 'Virgin River', 
    type: 'series', 
    genre: 'drama', 
    rating: 7.4, 
    year: 2019, 
    seasons: 5, 
    episodes: 54, 
    description: 'Seeking a fresh start, nurse practitioner Melinda Monroe moves from Los Angeles to a remote Northern California town and is surprised by what and who she finds.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjE1ZDVhZjQtYjc2Yi00MzljLWE3NzMtNTcyNzY5NzE2NzJlXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1550000 
  },
  { 
    id: 45, 
    title: 'Heartstopper', 
    type: 'series', 
    genre: 'drama', 
    rating: 8.6, 
    year: 2022, 
    seasons: 3, 
    episodes: 24, 
    description: 'Teens Charlie and Nick discover their unlikely friendship might be something more as they navigate school and young love in this coming-of-age series.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1650000 
  },

  // Thriller
  { 
    id: 46, 
    title: 'Mindhunter', 
    type: 'series', 
    genre: 'thriller', 
    rating: 8.6, 
    year: 2017, 
    seasons: 2, 
    episodes: 19, 
    description: 'In the late 1970s, two FBI agents broaden the realm of criminal science by investigating the psychology behind murder and end up getting too close to real-life monsters.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNWNmYzQ1ZWUtYTQ3ZS00Y2UwLTlkMDctZGUwNTlkMzUyNzJlXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1650000 
  },
  { 
    id: 47, 
    title: 'You', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.7, 
    year: 2018, 
    seasons: 4, 
    episodes: 40, 
    description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.', 
    image: 'https://m.media-amazon.com/images/M/MV5BODZlNGI0ZWQtMzQ3Mi00Y2YwLWE5NGEtMmE4Y2QwMTMxODEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1450000 
  },
  { 
    id: 48, 
    title: 'Bird Box', 
    type: 'movie', 
    genre: 'thriller', 
    rating: 6.6, 
    year: 2018, 
    runtime: 124, 
    description: 'Five years after an ominous unseen presence drives most of society to suicide, a mother and her two children make a desperate bid to reach safety.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1300000 
  },
  { 
    id: 49, 
    title: 'Dark', 
    type: 'series', 
    genre: 'thriller', 
    rating: 8.8, 
    year: 2017, 
    seasons: 3, 
    episodes: 26, 
    description: 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.', 
    image: 'https://m.media-amazon.com/images/M/MV5BOTk2NzUyOTctZDVjNy00OWQ0LTg2YjctMTE0NzNkZDc1ZjgzXkEyXkFqcGdeQXVyMjg1NDcxNDE@._V1_FMjpg_UX1000_.jpg', 
    popularity: 91, 
    viewingHours: 1900000 
  },
  { 
    id: 50, 
    title: 'The Platform', 
    type: 'movie', 
    genre: 'thriller', 
    rating: 7.0, 
    year: 2019, 
    runtime: 94, 
    description: 'A vertical prison with one cell per level. Two people per cell. Only one food platform and two minutes per day to feed. An endless nightmare trapped in The Hole.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 850000 
  },
  { 
    id: 51, 
    title: 'Locke & Key', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.4, 
    year: 2020, 
    seasons: 3, 
    episodes: 28, 
    description: 'After their father is murdered, three siblings move to their ancestral home in Massachusetts only to find the house has magical keys that give them a vast array of powers.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 80, 
    viewingHours: 1250000 
  },
  { 
    id: 52, 
    title: 'The Sinner', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.9, 
    year: 2017, 
    seasons: 4, 
    episodes: 32, 
    description: 'Anthology series that examines how and why ordinary people commit brutal crimes.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1350000 
  },
  { 
    id: 53, 
    title: 'Safe', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.2, 
    year: 2018, 
    seasons: 1, 
    episodes: 8, 
    description: 'After his teenage daughter goes missing, a desperate father tries to find her by following clues from her last known whereabouts.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 75, 
    viewingHours: 950000 
  },
  { 
    id: 54, 
    title: 'The Stranger', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.3, 
    year: 2020, 
    seasons: 1, 
    episodes: 8, 
    description: 'A secret destroys a man\'s perfect life and sends him on a collision course with a deadly conspiracy.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 77, 
    viewingHours: 1050000 
  },
  { 
    id: 55, 
    title: 'Elite', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.5, 
    year: 2018, 
    seasons: 7, 
    episodes: 64, 
    description: 'When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNWVmYzIzZGYtNGJkOS00NzI1LWE4ZjYtMGZjMzYzYWM1YWY0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1750000 
  },
  { 
    id: 56, 
    title: 'Bodyguard', 
    type: 'series', 
    genre: 'thriller', 
    rating: 8.0, 
    year: 2018, 
    seasons: 1, 
    episodes: 6, 
    description: 'A troubled war veteran is assigned to protect a controversial politician who may be the target of a conspiracy.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1150000 
  },
  { 
    id: 57, 
    title: 'The Keepers', 
    type: 'series', 
    genre: 'thriller', 
    rating: 8.2, 
    year: 2017, 
    seasons: 1, 
    episodes: 7, 
    description: 'A nun\'s murder in Baltimore opens the door to horrific secrets and pain that linger nearly five decades after her death.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyNTg2NjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 1000000 
  },
  { 
    id: 58, 
    title: 'Clickbait', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.2, 
    year: 2021, 
    seasons: 1, 
    episodes: 8, 
    description: 'When family man Nick Brewer is abducted in a crime with a sinister online twist, those closest to him race to uncover who is behind it and why.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 74, 
    viewingHours: 920000 
  },
  { 
    id: 59, 
    title: 'The Serpent', 
    type: 'series', 
    genre: 'thriller', 
    rating: 7.5, 
    year: 2021, 
    seasons: 1, 
    episodes: 8, 
    description: 'The twisting, real-life story of Charles Sobhraj, a murderer, thief and seductive master of disguise, who was a hidden darkness in the mid-70s on Asia\'s hippie trail.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 1150000 
  },
  { 
    id: 60, 
    title: 'Wednesday', 
    type: 'series', 
    genre: 'thriller', 
    rating: 8.1, 
    year: 2022, 
    seasons: 2, 
    episodes: 16, 
    description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjY0NDYzMzctYjE2OS00YWNlLWE4NzItZmZhY2Q3NjY3YzNkXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 95, 
    viewingHours: 2500000 
  },

  // Documentary
  { 
    id: 61, 
    title: 'Making a Murderer', 
    type: 'series', 
    genre: 'documentary', 
    rating: 8.6, 
    year: 2015, 
    seasons: 2, 
    episodes: 20, 
    description: 'Filmed over 10 years, this real-life thriller follows a DNA exoneree who, while exposing police corruption, becomes a suspect in a grisly new crime.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1750000 
  },
  { 
    id: 62, 
    title: 'Tiger King', 
    type: 'series', 
    genre: 'documentary', 
    rating: 7.5, 
    year: 2020, 
    seasons: 2, 
    episodes: 12, 
    description: 'A rivalry between big cat eccentrics takes a dark turn when Joe Exotic, a controversial animal park boss, is caught in a murder-for-hire plot.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 93, 
    viewingHours: 2050000 
  },
  { 
    id: 63, 
    title: 'My Octopus Teacher', 
    type: 'movie', 
    genre: 'documentary', 
    rating: 8.1, 
    year: 2020, 
    runtime: 85, 
    description: 'A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 920000 
  },
  { 
    id: 64, 
    title: 'The Social Dilemma', 
    type: 'movie', 
    genre: 'documentary', 
    rating: 7.6, 
    year: 2020, 
    runtime: 94, 
    description: 'Tech experts sound the alarm on their own creations. This documentary-drama hybrid explores the dangerous human impact of social networking.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1150000 
  },
  { 
    id: 65, 
    title: 'Wild Wild Country', 
    type: 'series', 
    genre: 'documentary', 
    rating: 8.2, 
    year: 2018, 
    seasons: 1, 
    episodes: 6, 
    description: 'When a controversial guru builds a utopian city in the Oregon desert, it causes a massive conflict with local ranchers. This docuseries reveals how it all went wrong.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 80, 
    viewingHours: 1050000 
  },
  { 
    id: 66, 
    title: 'American Murder: The Family Next Door', 
    type: 'movie', 
    genre: 'documentary', 
    rating: 7.3, 
    year: 2020, 
    runtime: 82, 
    description: 'Using raw, firsthand footage, this documentary examines the disappearance of Shanann Watts and her children, and the terrible events that followed.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1200000 
  },
  { 
    id: 67, 
    title: 'Fyre: The Greatest Party That Never Happened', 
    type: 'movie', 
    genre: 'documentary', 
    rating: 7.7, 
    year: 2019, 
    runtime: 97, 
    description: 'An exclusive behind the scenes look at the infamous unraveling of the Fyre music festival.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 980000 
  },
  { 
    id: 68, 
    title: 'The Tinder Swindler', 
    type: 'movie', 
    genre: 'documentary', 
    rating: 7.1, 
    year: 2022, 
    runtime: 114, 
    description: 'Posing as a wealthy, jet-setting diamond mogul, he wooed women online then conned them out of millions of dollars. Now some victims plan for payback.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1350000 
  },
  { 
    id: 69, 
    title: 'Don\'t F**k with Cats', 
    type: 'series', 
    genre: 'documentary', 
    rating: 8.0, 
    year: 2019, 
    seasons: 1, 
    episodes: 3, 
    description: 'A group of online justice seekers track down a man who posted a video of himself killing kittens.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 85, 
    viewingHours: 1150000 
  },
  { 
    id: 70, 
    title: 'The Disappearance of Madeleine McCann', 
    type: 'series', 
    genre: 'documentary', 
    rating: 6.6, 
    year: 2019, 
    seasons: 1, 
    episodes: 8, 
    description: 'The documentary takes a detailed look at the disappearance of 3-year-old Madeleine McCann, who vanished from the seaside resort of Praia de Luz in Portugal.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 1050000 
  },
  { 
    id: 71, 
    title: 'Conversations with a Killer: The Ted Bundy Tapes', 
    type: 'series', 
    genre: 'documentary', 
    rating: 7.7, 
    year: 2019, 
    seasons: 1, 
    episodes: 4, 
    description: 'A look inside the mind of serial killer Ted Bundy, featuring interviews with him on death row.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1250000 
  },
  { 
    id: 72, 
    title: 'The Staircase', 
    type: 'series', 
    genre: 'documentary', 
    rating: 8.2, 
    year: 2018, 
    seasons: 1, 
    episodes: 13, 
    description: 'Academy Award-winning documentary filmmaker Jean-Xavier de Lestrade presents a gripping courtroom thriller.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 1450000 
  },
  { 
    id: 73, 
    title: 'Evil Genius', 
    type: 'series', 
    genre: 'documentary', 
    rating: 7.5, 
    year: 2018, 
    seasons: 1, 
    episodes: 4, 
    description: 'This baffling true crime story starts with the grisly death of a pizza man who robs a bank with a bomb around his neck.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 76, 
    viewingHours: 950000 
  },
  { 
    id: 74, 
    title: 'The Keepers', 
    type: 'series', 
    genre: 'documentary', 
    rating: 8.2, 
    year: 2017, 
    seasons: 1, 
    episodes: 7, 
    description: 'A nun\'s murder in Baltimore opens the door to horrific secrets and pain that linger nearly five decades after her death.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1350000 
  },
  { 
    id: 75, 
    title: 'Our Planet', 
    type: 'series', 
    genre: 'documentary', 
    rating: 9.3, 
    year: 2019, 
    seasons: 1, 
    episodes: 8, 
    description: 'Experience our planet\'s natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjExMTM3NDAzOF5BMl5BanBnXkFtZTgwNTM3MTY3NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1650000 
  },

  // Romance
  { 
    id: 76, 
    title: 'Bridgerton', 
    type: 'series', 
    genre: 'romance', 
    rating: 7.3, 
    year: 2020, 
    seasons: 3, 
    episodes: 24, 
    description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 94, 
    viewingHours: 2300000 
  },
  { 
    id: 77, 
    title: 'To All the Boys I\'ve Loved Before', 
    type: 'movie', 
    genre: 'romance', 
    rating: 7.0, 
    year: 2018, 
    runtime: 99, 
    description: 'A teenage girl\'s secret love letters are exposed and wreak havoc on her love life.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjQ4NzcxMjktYjI5Yi00NGY0LWI4NWYtZDI2NzVlYjU4NmY0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 
    popularity: 85, 
    viewingHours: 1200000 
  },
  { 
    id: 78, 
    title: 'Emily in Paris', 
    type: 'series', 
    genre: 'romance', 
    rating: 6.8, 
    year: 2020, 
    seasons: 4, 
    episodes: 40, 
    description: 'After landing her dream job in Paris, Chicago marketing exec Emily Cooper embraces her adventurous new life while juggling work, friends and romance.', 
    image: 'https://m.media-amazon.com/images/M/MV5BODc4YmE0NWItYzBhZC00YzY0LThlNWItZDRjMDExMzQ1MjdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 1400000 
  },
  { 
    id: 79, 
    title: 'The Half of It', 
    type: 'movie', 
    genre: 'romance', 
    rating: 6.9, 
    year: 2020, 
    runtime: 104, 
    description: 'A shy student helps the sweet jock woo the girl they both like.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 77, 
    viewingHours: 780000 
  },
  { 
    id: 80, 
    title: 'Virgin River', 
    type: 'series', 
    genre: 'romance', 
    rating: 7.4, 
    year: 2019, 
    seasons: 5, 
    episodes: 54, 
    description: 'Seeking a fresh start, nurse practitioner Melinda Monroe moves from Los Angeles to a remote Northern California town and is surprised by what and who she finds.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjE1ZDVhZjQtYjc2Yi00MzljLWE3NzMtNTcyNzY5NzE2NzJlXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1550000 
  },
  { 
    id: 81, 
    title: 'The Kissing Booth 2', 
    type: 'movie', 
    genre: 'romance', 
    rating: 5.7, 
    year: 2020, 
    runtime: 132, 
    description: 'With college decisions looming, Elle juggles her long-distance romance with Noah, changing friendship with Lee and feelings for a new classmate.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 950000 
  },
  { 
    id: 82, 
    title: 'Always Be My Maybe', 
    type: 'movie', 
    genre: 'romance', 
    rating: 6.8, 
    year: 2019, 
    runtime: 101, 
    description: 'Reunited after 15 years, famous chef Sasha and hometown musician Marcus feel the old sparks of attraction but struggle to adapt to each other\'s worlds.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 80, 
    viewingHours: 1050000 
  },
  { 
    id: 83, 
    title: 'Set It Up', 
    type: 'movie', 
    genre: 'romance', 
    rating: 6.5, 
    year: 2018, 
    runtime: 105, 
    description: 'Two corporate executive assistants hatch a plan to match-make their two bosses.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1150000 
  },
  { 
    id: 84, 
    title: 'The Perfect Date', 
    type: 'movie', 
    genre: 'romance', 
    rating: 5.8, 
    year: 2019, 
    runtime: 89, 
    description: 'To save up for college, Brooks Rattigan creates an app where anyone can pay him to play the perfect stand-in boyfriend for any occasion.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 74, 
    viewingHours: 850000 
  },
  { 
    id: 85, 
    title: 'Purple Hearts', 
    type: 'movie', 
    genre: 'romance', 
    rating: 6.7, 
    year: 2022, 
    runtime: 122, 
    description: 'In spite of their many differences, Cassie, a struggling singer-songwriter, and Luke, a troubled Marine, agree to marry solely for military benefits.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjQ0NzQ3NjYtYzc5OS00YjJmLTg0ODEtNjM2NWQ5NTg4NWZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1350000 
  },

  // Horror
  { 
    id: 86, 
    title: 'The Haunting of Hill House', 
    type: 'series', 
    genre: 'horror', 
    rating: 8.6, 
    year: 2018, 
    seasons: 1, 
    episodes: 10, 
    description: 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1650000 
  },
  { 
    id: 87, 
    title: 'His House', 
    type: 'movie', 
    genre: 'horror', 
    rating: 6.5, 
    year: 2020, 
    runtime: 93, 
    description: 'A refugee couple makes a harrowing escape from war-torn South Sudan, but then they struggle to adjust to their new life in an English town that has an evil lurking beneath the surface.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 74, 
    viewingHours: 680000 
  },
  { 
    id: 88, 
    title: 'Midnight Mass', 
    type: 'series', 
    genre: 'horror', 
    rating: 7.7, 
    year: 2021, 
    seasons: 1, 
    episodes: 7, 
    description: 'An isolated island community experiences miraculous events - and frightening omens - after the arrival of a charismatic, mysterious young priest.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 950000 
  },
  { 
    id: 89, 
    title: 'Fear Street Trilogy', 
    type: 'movie', 
    genre: 'horror', 
    rating: 6.7, 
    year: 2021, 
    runtime: 107, 
    description: 'A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1100000 
  },
  { 
    id: 90, 
    title: 'The Ritual', 
    type: 'movie', 
    genre: 'horror', 
    rating: 6.3, 
    year: 2017, 
    runtime: 94, 
    description: 'A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods that\'s stalking them.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 71, 
    viewingHours: 620000 
  },
  { 
    id: 91, 
    title: 'The Haunting of Bly Manor', 
    type: 'series', 
    genre: 'horror', 
    rating: 7.4, 
    year: 2020, 
    seasons: 1, 
    episodes: 9, 
    description: 'After an au pair\'s tragic death, Henry hires a young American nanny to care for his orphaned niece and nephew who reside at Bly Manor with the chef Owen, groundskeeper Jamie and housekeeper, Mrs. Grose.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 83, 
    viewingHours: 1250000 
  },
  { 
    id: 92, 
    title: 'Cam', 
    type: 'movie', 
    genre: 'horror', 
    rating: 5.9, 
    year: 2018, 
    runtime: 94, 
    description: 'Alice, an ambitious camgirl, wakes up one day to discover she\'s been replaced on her show with an exact replica of herself.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 68, 
    viewingHours: 580000 
  },
  { 
    id: 93, 
    title: 'Apostle', 
    type: 'movie', 
    genre: 'horror', 
    rating: 6.3, 
    year: 2018, 
    runtime: 130, 
    description: 'In 1905, a drifter on a dangerous mission to rescue his kidnapped sister tangles with a sinister religious cult on an isolated island.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 72, 
    viewingHours: 750000 
  },
  { 
    id: 94, 
    title: 'Marianne', 
    type: 'series', 
    genre: 'horror', 
    rating: 7.5, 
    year: 2019, 
    seasons: 1, 
    episodes: 8, 
    description: 'When a novelist realizes her terrifying stories are coming true, she returns to her hometown to face the demon that could be real.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 76, 
    viewingHours: 950000 
  },
  { 
    id: 95, 
    title: 'In the Tall Grass', 
    type: 'movie', 
    genre: 'horror', 
    rating: 5.4, 
    year: 2019, 
    runtime: 101, 
    description: 'After hearing a young boy\'s cry for help, a sister and brother venture into a vast field of tall grass to rescue him, but soon discover there may be no way out.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 69, 
    viewingHours: 650000 
  },

  // Sci-Fi
  { 
    id: 96, 
    title: 'Black Mirror', 
    type: 'series', 
    genre: 'sci-fi', 
    rating: 8.8, 
    year: 2011, 
    seasons: 6, 
    episodes: 27, 
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 92, 
    viewingHours: 2100000 
  },
  { 
    id: 97, 
    title: 'Lost in Space', 
    type: 'series', 
    genre: 'sci-fi', 
    rating: 7.3, 
    year: 2018, 
    seasons: 3, 
    episodes: 28, 
    description: 'After crash-landing on an alien planet, the Robinson family fight against all odds to survive and escape, but they\'re surrounded by hidden dangers.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjM5NDA4NzQwOV5BMl5BanBnXkFtZTgwNjkyNzQzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 80, 
    viewingHours: 1350000 
  },
  { 
    id: 98, 
    title: 'The Midnight Sky', 
    type: 'movie', 
    genre: 'sci-fi', 
    rating: 5.7, 
    year: 2020, 
    runtime: 118, 
    description: 'A lonely scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTEwZjkxNzEtYzc3MS00ZmY0LWIwNzMtZWE1NjBiNjkwZjJkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 73, 
    viewingHours: 750000 
  },
  { 
    id: 99, 
    title: 'Altered Carbon', 
    type: 'series', 
    genre: 'sci-fi', 
    rating: 8.0, 
    year: 2018, 
    seasons: 2, 
    episodes: 18, 
    description: 'After 250 years on ice, a prisoner returns to life in a new body with one chance to win his freedom: by solving a mind-bending murder.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTk2NDQ4MTc2NV5BMl5BanBnXkFtZTgwNDk4OTYxNTM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1450000 
  },
  { 
    id: 100, 
    title: 'Stowaway', 
    type: 'movie', 
    genre: 'sci-fi', 
    rating: 5.6, 
    year: 2021, 
    runtime: 116, 
    description: 'A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTEwZjkxNzEtYzc3MS00ZmY0LWIwNzMtZWE1NjBiNjkwZjJkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 69, 
    viewingHours: 580000 
  },
  { 
    id: 101, 
    title: 'The OA', 
    type: 'series', 
    genre: 'sci-fi', 
    rating: 7.8, 
    year: 2016, 
    seasons: 2, 
    episodes: 16, 
    description: 'Seven years after vanishing from her home, a young woman returns with mysterious new abilities and recruits five strangers for a secret mission.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjM5NDA4NzQwOV5BMl5BanBnXkFtZTgwNjkyNzQzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 1150000 
  },
  { 
    id: 102, 
    title: 'I Am Mother', 
    type: 'movie', 
    genre: 'sci-fi', 
    rating: 6.7, 
    year: 2019, 
    runtime: 113, 
    description: 'A teenage girl is raised underground by a robot "Mother", designed to repopulate the earth following an extinction event.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTEwZjkxNzEtYzc3MS00ZmY0LWIwNzMtZWE1NjBiNjkwZjJkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 75, 
    viewingHours: 850000 
  },
  { 
    id: 103, 
    title: 'Another Life', 
    type: 'series', 
    genre: 'sci-fi', 
    rating: 5.4, 
    year: 2019, 
    seasons: 2, 
    episodes: 20, 
    description: 'After a massive alien artifact lands on Earth, Niko Breckinridge leads an interstellar mission to track down its source and make first contact.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjM5NDA4NzQwOV5BMl5BanBnXkFtZTgwNjkyNzQzNjM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 67, 
    viewingHours: 950000 
  },
  { 
    id: 104, 
    title: 'Oxygen', 
    type: 'movie', 
    genre: 'sci-fi', 
    rating: 6.5, 
    year: 2021, 
    runtime: 100, 
    description: 'A woman wakes up in a cryogenic pod with no memory of how she got there, and must find a way out before running out of air.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTEwZjkxNzEtYzc3MS00ZmY0LWIwNzMtZWE1NjBiNjkwZjJkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 71, 
    viewingHours: 720000 
  },
  { 
    id: 105, 
    title: 'The Silence', 
    type: 'movie', 
    genre: 'sci-fi', 
    rating: 5.3, 
    year: 2019, 
    runtime: 90, 
    description: 'When the world is under attack from creatures who hunt by sound, a teen and her family seek refuge outside the city and encounter a mysterious cult.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTEwZjkxNzEtYzc3MS00ZmY0LWIwNzMtZWE1NjBiNjkwZjJkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 68, 
    viewingHours: 650000 
  },

  // Animation
  { 
    id: 106, 
    title: 'BoJack Horseman', 
    type: 'series', 
    genre: 'animation', 
    rating: 8.8, 
    year: 2014, 
    seasons: 6, 
    episodes: 77, 
    description: 'Meet the most beloved sitcom horse of the \'90s, 20 years later. He\'s a curmudgeon with a heart of... not quite gold... but something like gold.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYWQwMDNkM2MtODU4OS00OTY3LTgwOTItNjE2Yzc0MzRkMDllXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1800000 
  },
  { 
    id: 107, 
    title: 'Klaus', 
    type: 'movie', 
    genre: 'animation', 
    rating: 8.2, 
    year: 2019, 
    runtime: 96, 
    description: 'A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg\'s new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMWYwOThjM2ItZGYxNy00NTQwLWFlZWEtM2MzM2Q5MmY3NDU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 86, 
    viewingHours: 1250000 
  },
  { 
    id: 108, 
    title: 'Big Mouth', 
    type: 'series', 
    genre: 'animation', 
    rating: 7.8, 
    year: 2017, 
    seasons: 7, 
    episodes: 71, 
    description: 'Teenage friends find their lives upended by the wonders and horrors of puberty in this edgy comedy from real-life pals Nick Kroll and Andrew Goldberg.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1500000 
  },
  { 
    id: 109, 
    title: 'The Mitchells vs. The Machines', 
    type: 'movie', 
    genre: 'animation', 
    rating: 7.6, 
    year: 2021, 
    runtime: 113, 
    description: 'A quirky, dysfunctional family\'s road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity\'s unlikeliest last hope.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMjQyODg5Njc4NF5BMl5BanBnXkFtZTgwNzE4NDI0NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1180000 
  },
  { 
    id: 110, 
    title: 'Castlevania', 
    type: 'series', 
    genre: 'animation', 
    rating: 8.3, 
    year: 2017, 
    seasons: 4, 
    episodes: 32, 
    description: 'A vampire hunter fights to save a besieged city from an army of otherworldly creatures controlled by Dracula.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNTUyMzExMDMtMDU5Yy00NGNlLWI0ZmQtZWExNzg5YzQyYzAyXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg', 
    popularity: 87, 
    viewingHours: 1650000 
  },
  { 
    id: 111, 
    title: 'F is for Family', 
    type: 'series', 
    genre: 'animation', 
    rating: 8.0, 
    year: 2015, 
    seasons: 5, 
    episodes: 44, 
    description: 'Follow the Murphy family back to the 1970s, when kids roamed wild, beer flowed freely and nothing came between a man and his TV.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 79, 
    viewingHours: 1200000 
  },
  { 
    id: 112, 
    title: 'Disenchantment', 
    type: 'series', 
    genre: 'animation', 
    rating: 7.2, 
    year: 2018, 
    seasons: 5, 
    episodes: 50, 
    description: 'Princess Bean is dreaming of adventure and true love. Along with her elf companion Elfo and her personal demon Luci, Bean flees the kingdom of Dreamland for a series of misadventures.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 76, 
    viewingHours: 1350000 
  },
  { 
    id: 113, 
    title: 'Love, Death & Robots', 
    type: 'series', 
    genre: 'animation', 
    rating: 8.4, 
    year: 2019, 
    seasons: 3, 
    episodes: 35, 
    description: 'Terrifying creatures, wicked surprises and dark comedy converge in this NSFW anthology of animated stories presented by Tim Miller and David Fincher.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMTc1MjIyNDI3Nl5BMl5BanBnXkFtZTgwMjQ1OTI0NzM@._V1_FMjpg_UX1000_.jpg', 
    popularity: 88, 
    viewingHours: 1550000 
  },
  { 
    id: 114, 
    title: 'Arcane', 
    type: 'series', 
    genre: 'animation', 
    rating: 9.0, 
    year: 2021, 
    seasons: 2, 
    episodes: 18, 
    description: 'Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.', 
    image: 'https://m.media-amazon.com/images/M/MV5BYmU5OWM5ZTAtNjUzOC00NmUyLTgyOWMtMjlkNjdlMDAzMzU1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 94, 
    viewingHours: 2200000 
  },
  { 
    id: 115, 
    title: 'The Dragon Prince', 
    type: 'series', 
    genre: 'animation', 
    rating: 8.3, 
    year: 2018, 
    seasons: 6, 
    episodes: 63, 
    description: 'An extraordinary discovery inspires two human princes and an elven assassin to team up on an epic quest to bring peace to their warring lands.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 81, 
    viewingHours: 1450000 
  },

  // Recent Popular Additions
  { 
    id: 116, 
    title: 'Glass Onion: A Knives Out Mystery', 
    type: 'movie', 
    genre: 'thriller', 
    rating: 7.2, 
    year: 2022, 
    runtime: 139, 
    description: 'Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island. When someone turns up dead, Detective Benoit Blanc is put on the case.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 89, 
    viewingHours: 1650000 
  },
  { 
    id: 117, 
    title: 'The Sandman', 
    type: 'series', 
    genre: 'horror', 
    rating: 7.7, 
    year: 2022, 
    seasons: 1, 
    episodes: 10, 
    description: 'After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 85, 
    viewingHours: 1450000 
  },
  { 
    id: 118, 
    title: 'Enola Holmes 2', 
    type: 'movie', 
    genre: 'action', 
    rating: 6.8, 
    year: 2022, 
    runtime: 129, 
    description: 'Now a detective-for-hire, Enola Holmes takes on her first official case to find a missing girl as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 82, 
    viewingHours: 1250000 
  },
  { 
    id: 119, 
    title: 'The Empress', 
    type: 'series', 
    genre: 'drama', 
    rating: 7.0, 
    year: 2022, 
    seasons: 2, 
    episodes: 12, 
    description: 'When rebellious Elisabeth falls for Emperor Franz and becomes Empress of Austria, she must learn to navigate the treacherous politics of the Viennese court.', 
    image: 'https://m.media-amazon.com/images/M/MV5BNjEwMzA5NDYtZjQ5ZC00ZjNhLWE4NzYtMGQ4YzQxYWI5YzA2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 
    popularity: 78, 
    viewingHours: 1150000 
  },
  { 
    id: 120, 
    title: 'All Quiet on the Western Front', 
    type: 'movie', 
    genre: 'drama', 
    rating: 7.8, 
    year: 2022, 
    runtime: 148, 
    description: 'A young German soldier\'s terrifying experiences and distress on the western front during World War I.', 
    image: 'https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzI5LWEzYTMtN2YwZjAyZmZkYzE3XkEyXkFqcGdeQXVyMTUzMTg2ODkz@._V1_FMjpg_UX1000_.jpg', 
    popularity: 84, 
    viewingHours: 1350000 
  }
];

export class ContentManager {
  constructor() {
    this.allContent = [...netflixContent];
    this.filteredContent = [...netflixContent];
    this.currentGenre = 'all';
    this.currentSearchTerm = '';
    this.currentSortBy = 'title';
  }

  filterContent(searchTerm = '', genre = 'all', sortBy = 'title') {
    this.currentSearchTerm = searchTerm.toLowerCase();
    this.currentGenre = genre;
    this.currentSortBy = sortBy;

    let filtered = this.allContent.filter(content => {
      const matchesSearch = content.title.toLowerCase().includes(this.currentSearchTerm) ||
                           content.description.toLowerCase().includes(this.currentSearchTerm);
      const matchesGenre = genre === 'all' || content.genre === genre;
      
      return matchesSearch && matchesGenre;
    });

    // Sort content
    filtered = this.sortContent(filtered, sortBy);
    
    this.filteredContent = filtered;
    return filtered;
  }

  sortContent(content, sortBy) {
    const sorted = [...content];
    
    switch (sortBy) {
      case 'rating-low':
        return sorted.sort((a, b) => a.rating - b.rating);
      case 'rating-high':
        return sorted.sort((a, b) => b.rating - a.rating);
      case 'year':
        return sorted.sort((a, b) => b.year - a.year);
      case 'popularity':
        return sorted.sort((a, b) => b.popularity - a.popularity);
      case 'title':
      default:
        return sorted.sort((a, b) => a.title.localeCompare(b.title));
    }
  }

  highlightSearchTerm(text, searchTerm) {
    if (!searchTerm) return text;
    
    const regex = new RegExp(`(${searchTerm})`, 'gi');
    return text.replace(regex, '<span class="highlight">$1</span>');
  }

  getFilteredContent() {
    return this.filteredContent;
  }

  getContentCount() {
    return this.filteredContent.length;
  }

  getTotalContentCount() {
    return this.allContent.length;
  }
}